### ISSUE TITLE
Local files only

### ISSUE THREAD

**Issue by davidrussell** [bliswebagency/Download-File#1]
This plugin seems to work great, except that it only allows for files to be downloaded if they are on the same server (related to the server path) that EE runs on. We store our files on an external server and use a subdomain for accessing them. Can this plugin be tweaked to accommodate externally hosted files?

**Comment by bliswebagency** [comment]
Hi David,

Your scenario hadn't occurred to us but I agree that given an environment where you're not working on the production server, being able to protect a remote path could be very handy. We're currently working on a couple of big, new things at the moment for EE but once they're live we'll certainly return to Download File and implement a few new features like this for you.

Kind regards,

Sam Lomax

Blis Web Agency
Web Design | E-Commerce | CMS | Apps (iPhone/iPad)

8 Montrose Ave, Norwood SA 5067
Tel. (08) 8362 5688
Web. www.blis.net.au
