### ISSUE TITLE
Allow underscores and dashes in file

### ISSUE THREAD

**Issue by nixonmedia** [bliswebagency/Download-File#13]
Hi there, 

I'm not sure if you're still supporting this plugin, but I thought I would try any way. Is there anything I can do to allow underscores and dashes in file names?

**Comment by nixonmedia** [comment]
Actually, underscores and dashes are fine. It's () causing problems, example:
(Mastered) renders as %28Mastered%29

**Comment by bliswebagency** [comment]
I think you'll need to avoid files with brackets sorry. As a URL they'll always need to be encoded as an entity.—

**Comment by nixonmedia** [comment]
Ok. Thanks for the quick response.
