### ISSUE TITLE
Path correct in field, but 404 on embed page

### ISSUE THREAD

**Issue by jtrascap** [bliswebagency/Download-File#4]
I'm having a heck of a time using this. In my template, inside the standard {exp:channel:entries} loop I've got the link:

`<a href="{exp:download_file:link file='{track_file}' template='/embeds/download/'}">Download</a>`

pointing to a Matrix field, which does resolve perfectly well without the {download_file}-bit. Click on the link and on the embed/download template I receive the 404:

```Not Found

The requested URL /embeds/download/czo0ODoiaHR0cDovL3d3dy5mdW1iYXRhLmNvbS9hc3NldHMvZ2VzdGF0aW9uL3dvbWIubXAzIjs_ was not found on this server.```

I've been discussing it with others on devot-ee, but as there's no support there I hope this might be the best way... I'd appreciate any suggestions on how to debug this further...

**Comment by bliswebagency** [comment]
Hi JTrascap. Yes, I must close down the Devot:ee forum - I don't get notifications when anyone posts anything on there...! I'd also prefer the support to all be in the one place.

First up, I should say that although we've had a great experience with this addon, it appears that there may be some server environments we've not come across which have issues with it. 

Now, before I get too far into things; have you masked your index.php file using a .htaccess file?

**Comment by jtrascap** [comment]
For the record, it's Jim..  :) 

Anyway, I'm running on enginehosting.com, expression engine's own setup. Also, I've not yet done anything with index.php; it's still the site's index page. Also, using the latest ee (2.2.2), as well as the latest Matrix & Playa extensions.

**Comment by bliswebagency** [comment]
Great, thanks Jim.

What happens when you change your link to this:

```
<a href="{exp:download_file:link file='{track_file}' template='/index.php/embeds/download/'}">Download</a>
```

**Comment by jtrascap** [comment]
I get a standard ee severity error:

```A PHP Error was encountered

Severity: Warning

Message: file_get_contents(/www/public_htmlhttp://www.xxx.com/assets/album_02_GetUp/1-01 180 Promo.mp3): failed to open stream: No such file or directory

Filename: download_file/pi.download_file.php

Line Number: 65```

**Comment by jtrascap** [comment]
Noticed that the file has spaces in it, so I tried another file:

```A PHP Error was encountered

Severity: Warning

Message: file_get_contents(/www/public_htmlhttp://www.xxx.com/assets/album_04_Dictator/01_Hardliner.mp3): failed to open stream: No such file or directory

Filename: download_file/pi.download_file.php

Line Number: 65```

(BTW - I edited my url to not expose it...)

And I see the error in the path... I take it it's not using the server path normally...

**Comment by bliswebagency** [comment]
Ok, we're getting there. Now we need to remove the domain name from that path. 

```
<a href="{exp:download_file:link file='{track_file}' template='/index.php/embeds/download/' remove='http://www.xxx.com'}">Download</a>
```

**Comment by bliswebagency** [comment]
I just "adjusted" your domain to match your alias. You'll need to edit the string above before using it so that it includes the correct domain.

**Comment by jtrascap** [comment]
Boom! That was it... brilliant. I see how this is working now and will fill the others in on devot-ee (and point them here)

Thanks for the excellent help and swift response!

**Comment by bliswebagency** [comment]
Happy to help. Sorry the Devot:ee support was so crappy! I'll close this off now but if you need anything else, just post here again.

**Comment by jtrascap** [comment]
Hey - no worries. Your support was exemplary. Of course, you want to keep all your support here, and EE users want to keep all their support on devot-ee (now that third-party support has been kicked off ee's own forums for the most part, it makes some sense...)  Maybe just poke your head in there occasionally and set up a Support link on the page?  Thanks again!

**Comment by eastwooddesign** [comment]
having the same issue
< - a href="{exp:download_file:link file='{video_source}' template='/Media/download/' remove='http://domainA.ca/'}">Download MP4 <img src="http://www.domainA.ca/images/download.jpg" border="0" align="absmiddle" class="noshadow"/>< - /a>

then

Not Found

The requested URL /Media/download/czo3NToiaHR0cDovL3d3dy5uZXdjb3ZlbmFudGNodXJjaC5jYS9wb2RjYXN0cy9rbHZpZGVvLzIwMTItMDYtMTdfS0wtMjAxMi0wMjUubXA0Ijs_ was not found on this server.

If I add index.php ie: template='/index.php/Media/download/' The 404 error goes away but then it just loads a blank white page

For the MSM: the domain I am using this plugin on is domainA.ca and the file source is coming from another domain domainB.ca

Using MSM and EE 2.5.2
