### ISSUE TITLE
Remove the Directory Names from the Downloaded File?

### ISSUE THREAD

**Issue by bcrabtree** [bliswebagency/Download-File#5]
Hi,

This plug-in was just what I was looking for, awesome job. :) But I was wondering if it is possible to remove the directory names that are added to the downloaded file name.

For example, my typical image file path is something like:
http://www.mywebsite.com/images/uploads/photography/filename.jpg

Which when I download an image using your plug-in it creates a new file name like so:
_images_uploads_photography_filename.jpg

But I would like the downloaded file to be just:
filename.jpg

Let me know if you can help me out.

Cheers,
Bryan

**Comment by bliswebagency** [comment]
Hi Bryan,

I've pushed out a quick update which should help you out. Change the tag you're using on the page to serve the file to:

{exp:download_file:serve restricted="mydomain.com" prepend="mysite_" remove_path="/assets/"}

In your case, you'd need to change "/assets/" to whatever you're using for your path.

This is a beta update so please keep me posted on whether the changes have caused any other unforeseen issues.

**Comment by bcrabtree** [comment]
Awesome! Thank you.

So far so good. Seems to be working perfectly at the moment. I'll let you know if any issues pop up.

Cheers,
Bryan
