### ISSUE TITLE
filename includes the path to the image with dashes

### ISSUE THREAD

**Issue by neybox** [bliswebagency/Download-File#6]
I'm running ee v.2.1.3 with Download File Plugin v.1.0.2
The main problem is that the file downloaded is renamed to include it's path. 
eg.
file: /images/uploads/photogallery/1.jpg
gets downloaded as:
_images_uploads_photogallery_1.jpg

Parameters 'prepend' and 'remove' do nothing at all
Why is this happening?

**Comment by bliswebagency** [comment]
Hi Neybox, I think this thread should have you set in the right direction: https://github.com/bliswebagency/Download-File/issues/5

If that doesn't help, feel free to post again.
