### ISSUE TITLE
No such file or directory PHP Error

### ISSUE THREAD

**Issue by bcrabtree** [bliswebagency/Download-File#8]
Hi,

I'm getting a weird PHP error when I try to use this plugin on a new site I'm building. Basically it is saying that the file doesn't exist and shows the server file path to the file, but then if I check the server, the file is right there in that exact location...

I'm running 2.5.0, but I don't think that's the issue because I'm running 2.5.0 on another site with almost the same setup and it works just fine over there... weird. The only difference is that this is being used in multi-file P&T Assets field and the one that works is used in a P&T Matrix Field.

Here's the error message:

---

A PHP Error was encountered

Severity: Warning

Message: file_get_contents(/server_path/client_assets/Test%20Folder%202/ee_login_bg.gif) [function.file-get-contents]: failed to open stream: No such file or directory

Filename: download_file/pi.download_file.php

Line Number: 66

---

Here's my download link:
{exp:download_file:link file='{file:url}' template='/includes/download/' remove='http://www.mywebsite.com'}

Here's my template code:
{exp:download_file:serve restricted="mywebsite.com" remove_path="/client_assets/"}

**Comment by bcrabtree** [comment]
Nevermind, figured out the issue... Turns out it didn't like the spaces "%20" in my Assets created sub-directory... kind of a bummer because the client can name those folders whatever they want, but if they add spaces then it's going to break the download link.

Anyways, can you update the plugin to allow spaces? That would be awesome if you could ;)

Thanks!

**Comment by bliswebagency** [comment]
No problems, I'm hoping to push out a version with better Asset support this week. When I do so, I'll make sure it can handle spaces.
